# -*- coding: utf-8 -*-
"""Gonenc_Gerem_MIDTERM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CTve84SvxooGHtMjVvUEB7HJODOeX1Qf

*Hello*, please change the file name as your name_surname_MIDTERM.ipynb and upload to the folder 'DROP MIDTERMS HERE' on 
Drive.
ex: atay_ilgun_MIDTERM.ipynb

Also, create all TD related tasks on one TD file and upload it.
ex: atay_ilgun_MIDTERM.tox
"""

Gönenç Gerem

1317465

"""Describe what an algorithm is."""

Algorithm is a way to achieve solition for problems in computer sciences. 
Algorithm works according as it is instructed. It is executed the calculation according to set of rules which is given in advance.

"""Explain in what ways algorithmic design is different than the brute-force regular design approach. [50 words]"""

It can be identified as man powered generative solution and machine powered generative solution. If there is problem to solve or a design to make, we can specify the rules of the world of the problem/design 
and we can ask to the algorithm to generate a solution or a design, however in Brute-force is a general way to approach to the solution. It is only works on what is given in advance. It is always looking for a solution inside the provided information. 
But, for an algorithm is enough to provide the rules, it will "generate" the solution for you.

"""In 100 words meditate on how an new approach on design such as one that is algorithmic could affect your work practice."""

Algorithm is powerfull tool for generativity. It can generate possibilities or variation that human kind can not. So, for example there is an artists called David Carson
who is created the perception of "Breaking the grid". He broke the orthodox design understanding. In this graphic language, you don't use any design rules. It is all about order in the caos. 
You randomise the elements but still the output understandable, readble and visible. So, my posssible usage of algorithm in this, I can code and algorithm that take the input such as Title, text, 
visual and other needed materials and create an poster or magazine cover design which is totally randomised but still understable and visually satisfying.

"""Create a python dictionary for your name surname and year of birth."""

info = {
  'name':'Gönenç',
  'surname':'Gerem',
  'birth year':'1994'
}
print(info['surname'])

"""Write a conditional so If the first letter of your name is 'a' print 'my initial is a!'"""

name = 'Gönenç Gerem'

name[0]

if name[0] == 'a|A': 
  print ('my initial is an A')

else:
  print ('Get the duck out of here')

"""Write a conditional so If your surnames letter count is divisable by 3 print 'it is divisible' if not 'not divisible'."""

surname = 'Gerem'

if len(surname)%3 == 1:
  print('it is divisible')
  
else:
  print('What are you talking about')

"""Change your year of birth to 2678."""

info.update({'birth year':'2678'})
print(info ['birth year'])

"""TOUCHDESIGNER TIME.

Create a red box [in geo comp] and make it emit particles with a birth rate of 2500.
"""



"""Import a moving image and a sound file in TD.
Add at least two filters to the image file.
Make 2 parameters of these filters responsive to the audio.
"""



"""Create a torus and modify its x-size with an LFO with the frequency of 0.75."""



"""Create a sphere and create an amorph moving shape using 'noise'."""





"""Create a box and apply an image texture on it."""